FROM rclone/rclone:latest
# O comando de montagem do rclone será especificado no docker-compose.yml.
# Esta imagem base já contém rclone e FUSE devidamente configurados.
# Não são necessárias etapas adicionais de instalação aqui para o rclone funcionar.