version: '3.9'

services:
  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - eda_default
    deploy:
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          memory: 1G

volumes:
  mongodb_data:

networks:
  eda_default:
    external: true
