version: "3.8"

services:
  gpu-utils:
    image: gpu-utils:0.1.0
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.gpu == true
      resources:
        reservations:
          generic_resources:
            - discrete_resource_spec:
                kind: gpu
                value: 1
    networks:
      - ds_network

networks:
  ds_network:
    external: true
